version: '3'

services:
  db:
    image: postgres:16
    container_name: database
    env_file:
      postgres.env
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: always

  main_service:
    build:
      context: ./main_service
    container_name: main_service
    env_file:
      - main_service/config/.env
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge