#version: '3'
#
#services:
#  db:
#    image: postgres:16
#    container_name: database
#    env_file:
#      postgres.env
#    ports:
#      - "5433:5432"
#    networks:
#      - app-network
#    restart: always
#
#  main_service:
#    build:
#      context: ./main_service
#    container_name: main_service
#    env_file:
#      - main_service/config/auth.env
#      - main_service/config/db.env
#      - main_service/config/superuser.env
#    ports:
#      - "8000:8000"
#    networks:
#      - app-network
#    depends_on:
#      - db
#
#networks:
#  app-network:
#    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data: