version: '3'

services:
  db:
    image: postgres:16
    container_name: database
    environment:
      - POSTGRES_DB=web_money_manager,web_currency_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=17215

    ports:
      - "5433:5432"
    restart: always

  main_service:
    build:
      context: ./main_service
    container_name: main_service
    ports:
      - "8000:8000"
    depends_on:
      - db

  currency_service:
    build:
      context: ./currency_service
    container_name: currency_service
    ports:
      - "8001:8001"
    depends_on:
      - db