"""Add operation column in tracker_table

Revision ID: b0f9566a5036
Revises: f6bbfd68da73
Create Date: 2024-08-15 13:38:03.440470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f9566a5036'
down_revision: Union[str, None] = 'f6bbfd68da73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_tracker', sa.Column('operation', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_tracker', 'operation')
    # ### end Alembic commands ###
