"""Add change_tracker_table

Revision ID: f6bbfd68da73
Revises: c7a4fe21ee3e
Create Date: 2024-08-14 22:42:31.905426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6bbfd68da73'
down_revision: Union[str, None] = 'c7a4fe21ee3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('changed_table', sa.String(), nullable=False),
    sa.Column('changed_id', sa.String(), nullable=False),
    sa.Column('changed_datetime', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('transaction', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table('change_tracker')
    # ### end Alembic commands ###
