"""Changed column name to rates

Revision ID: 35a73901b5a1
Revises: a7a9b9b08e8c
Create Date: 2024-08-25 15:29:32.195004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a73901b5a1'
down_revision: Union[str, None] = 'a7a9b9b08e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rate', sa.Column('rates', sa.JSON(), nullable=False))
    op.drop_column('exchange_rate', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rate', sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('exchange_rate', 'rates')
    # ### end Alembic commands ###
