"""Create access_tokens table

Revision ID: 31115579091e
Revises: f28930f9930e
Create Date: 2024-08-28 13:57:09.407389

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31115579091e'
down_revision: Union[str, None] = 'f28930f9930e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'access_token',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('token', sa.String(length=43), nullable=False, unique=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f("fk_access_token_user_id"), ondelete='CASCADE'),
    )
    op.create_index(op.f('ix_access_token_created_at'), 'access_token', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_token_created_at'), table_name='access_token')
    op.drop_table('access_token')
    # ### end Alembic commands ###
