"""Add month_limit and operation_type columns

Revision ID: 97bedfd52369
Revises: 123123123123
Create Date: 2024-08-15 15:57:41.346696

"""
from enum import Enum
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bedfd52369'
down_revision: Union[str, None] = '123123123123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class TransactionType(Enum):
    add = "ADD"
    sub = "SUB"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE transaction_type AS ENUM('add', 'sub')")
    op.add_column('transaction', sa.Column('operation_type', sa.Enum('add', 'sub', name='transaction_type')))
    op.add_column('user', sa.Column('month_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'month_limit')
    op.drop_column('transaction', 'operation_type')
    op.execute("DROP TYPE transaction_type")
    # ### end Alembic commands ###
